version: "3.5"
services:
  rotki.dnp.dappnode.eth:
    image: "rotki.dnp.dappnode.eth:0.1.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: v1.23.0
    volumes:
      - "rotki_data:/data"
      - "rotki_logs:/logs"
    restart: always
volumes:
  rotki_data: {}
  rotki_logs: {}
