version: "3.5"
services:
  rotki.dnp.dappnode.eth:
    image: "rotki.dnp.dappnode.eth:0.1.0"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.31.2
    volumes:
      - "rotki_data:/data"
      - "rotki_logs:/logs"
    environment:
      ROTKI_ACCEPT_DOCKER_RISK: 1
    restart: always
volumes:
  rotki_data: {}
  rotki_logs: {}
