version: "3.5"
services:
  rotki.dnp.dappnode.eth:
    image: rotki.dnp.dappnode.eth:0.1.0
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.40.1
    volumes:
      - rotki_data:/data
      - rotki_logs:/logs
    environment:
      ROTKI_ACCEPT_DOCKER_RISK: 1
      LOGLEVEL: info
    restart: unless-stopped
volumes:
  rotki_data: {}
  rotki_logs: {}
