version: "3.5"
services:
  rotki.dnp.dappnode.eth:
    image: rotki.dnp.dappnode.eth:0.1.29
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.33.0
    volumes:
      - rotki_data:/data
      - rotki_logs:/logs
    environment:
      ROTKI_ACCEPT_DOCKER_RISK: 1
      LOGLEVEL: info
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
volumes:
  rotki_data: {}
  rotki_logs: {}
